# Using the container-based Ubuntu 14.04 Trusty setup
language: shell
script:
  - cd FOSS-AG-ad
  - latexmk -pdf -f -latexoption="--interaction=nonstopmode"
  - cd ../LDD2017
  - latexmk -pdf -f -latexoption="--interaction=nonstopmode"
  - cd ../ophasews1718
  - latexmk -pdf -f -latexoption="--interaction=nonstopmode"
deploy:
  skip_cleanup: true
  provider: script
  script: wget https://raw.githubusercontent.com/foss-ag/script_deploy-artifact/master/deploy-artifact.sh ; sh deploy-artifact.sh FOSS-AG-ad/*.pdf ; sh deploy-artifact.sh LDD2017/*.pdf ; sh deploy-artifact.sh ophasews1718/*.pdf
  on:
    all_branches: true
addons:
  apt:
    packages: [texlive-full]
